import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { OpenInApp } from "./open-in-app";
import {
  getSandwich,
  getYouTubePreview,
  sandwichAppLink,
  type Sandwich,
  type SandwichLeg,
} from "./sandwich";

export const revalidate = 300;

type Params = { params: Promise<{ id: string }> };

// Drives the link preview shown in WhatsApp/iMessage/Twitter when the URL is
// pasted. Without these tags the share would unfurl as a bare domain.
export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { id } = await params;
  const sandwich = await getSandwich(id);
  if (!sandwich) {
    return { title: "Sandwich not found — Bread" };
  }
  const title = `${sandwich.name} — Bread`;
  const description =
    sandwich.summary ||
    "A sandwich portfolio on Bread. Open in the app to invest.";
  const url = `/s/${encodeURIComponent(sandwich.id)}`;
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: "Bread",
      type: "website",
    },
    twitter: {
      // Large card so X unfurls the thesis image generated by
      // ./opengraph-image.tsx. Next auto-injects the og:image / twitter:image
      // tags (URL + 1200×630 dimensions) from that file — keep it as the single
      // source of the preview image so X never falls back to a bare domain.
      card: "summary_large_image",
      title,
      description,
    },
  };
}

function weightPct(bps: number): string {
  return `${(bps / 100).toFixed(bps % 100 === 0 ? 0 : 1)}%`;
}

function LegRow({ leg }: { leg: SandwichLeg }) {
  const ticker = leg.symbol ?? leg.underlyingSymbol ?? null;
  const isShort = leg.side?.toLowerCase() === "short";
  return (
    <li className="flex items-center gap-3 py-3">
      <div className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-full bg-soft text-xs font-bold text-navy">
        {leg.imageUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={leg.imageUrl}
            alt=""
            className="h-full w-full object-cover"
          />
        ) : (
          (ticker ?? leg.label).slice(0, 2).toUpperCase()
        )}
      </div>
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-semibold text-navy">{leg.label}</p>
        {ticker ? (
          <p className="truncate text-xs text-muted">
            {isShort ? "Short " : ""}
            {ticker}
          </p>
        ) : null}
      </div>
      <span className="shrink-0 text-sm font-semibold tabular-nums text-navy">
        {weightPct(leg.weightBps)}
      </span>
    </li>
  );
}

// YouTube-style preview card for sandwiches born from a video: thumbnail with
// a play badge, then title + channel. The whole card opens the video.
async function VideoCard({ source }: { source: NonNullable<Sandwich["source"]> }) {
  const videoId = source.videoId!;
  const watchUrl = source.sourceUrl ?? `https://www.youtube.com/watch?v=${videoId}`;
  const preview = await getYouTubePreview(videoId);
  const title = preview.title ?? source.title ?? "Watch on YouTube";
  const channel = preview.author ?? source.authorName ?? source.authorHandle;

  return (
    <a
      href={watchUrl}
      target="_blank"
      rel="noopener noreferrer"
      className="group block overflow-hidden rounded-2xl border border-border bg-card glow-soft transition hover:-translate-y-0.5"
    >
      <div className="relative aspect-video w-full overflow-hidden bg-navy">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={preview.thumbnailUrl}
          alt={title}
          className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]"
        />
        <span className="absolute inset-0 bg-navy/10 transition group-hover:bg-navy/0" />
        <span className="absolute inset-0 flex items-center justify-center">
          <span className="flex h-12 w-[4.5rem] items-center justify-center rounded-xl bg-[#f00] shadow-lg transition group-hover:scale-110">
            <svg viewBox="0 0 24 24" className="ml-0.5 h-6 w-6 fill-white" aria-hidden>
              <path d="M8 5v14l11-7z" />
            </svg>
          </span>
        </span>
      </div>
      <div className="flex items-start gap-3 p-4">
        {source.authorAvatarUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={source.authorAvatarUrl}
            alt=""
            className="h-9 w-9 shrink-0 rounded-full bg-soft object-cover"
          />
        ) : null}
        <div className="min-w-0 flex-1">
          <p className="line-clamp-2 text-sm font-semibold leading-snug text-navy">{title}</p>
          <p className="mt-1 truncate text-xs text-muted">
            {channel ? `${channel} · ` : ""}Watch on YouTube ↗
          </p>
        </div>
      </div>
    </a>
  );
}

export default async function SandwichSharePage({ params }: Params) {
  const { id } = await params;
  const sandwich = await getSandwich(id);
  if (!sandwich) notFound();

  const pnl = sandwich.pnlPct;
  const pnlPositive = (pnl ?? 0) >= 0;
  const video =
    sandwich.source?.sourceType === "youtube" && sandwich.source.videoId
      ? sandwich.source
      : null;

  return (
    <main
      className={`mx-auto flex w-full flex-1 flex-col px-5 py-10 sm:py-16 ${
        video ? "max-w-4xl" : "max-w-xl"
      }`}
    >
      <p className="text-sm font-semibold uppercase tracking-wide text-accent-deep">
        🥪 Bread Sandwich
      </p>

      <h1 className="mt-3 text-3xl font-bold leading-tight text-navy sm:text-4xl">
        {sandwich.name}
      </h1>

      <div className="mt-3 flex flex-wrap items-center gap-2 text-xs font-semibold">
        {sandwich.direction ? (
          <span className="rounded-full bg-soft px-3 py-1 capitalize text-navy">
            {sandwich.direction}
          </span>
        ) : null}
        {sandwich.horizon ? (
          <span className="rounded-full bg-soft px-3 py-1 capitalize text-navy">
            {sandwich.horizon}
          </span>
        ) : null}
        {pnl !== null ? (
          <span
            className={`rounded-full px-3 py-1 tabular-nums ${
              pnlPositive ? "bg-accent/15 text-accent-deep" : "bg-magenta/10 text-magenta"
            }`}
          >
            {pnlPositive ? "+" : ""}
            {pnl.toFixed(2)}%
          </span>
        ) : null}
      </div>

      {sandwich.summary ? (
        <p className="mt-5 text-base leading-relaxed text-muted">
          {sandwich.summary}
        </p>
      ) : null}

      <div className={video ? "mt-8 grid gap-6 sm:grid-cols-2 sm:items-start" : "mt-8"}>
        {video ? (
          <div>
            <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">
              From this video
            </p>
            <VideoCard source={video} />
          </div>
        ) : null}

        {sandwich.legs.length > 0 ? (
          <div>
            {video ? (
              <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">
                The sandwich it inspired
              </p>
            ) : null}
            <div className="rounded-2xl border border-border bg-card p-5 glow-soft">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted">
                Basket · {sandwich.legs.length} positions
              </p>
              <ul className="mt-1 divide-y divide-border">
                {sandwich.legs.map((leg) => (
                  <LegRow key={leg.id} leg={leg} />
                ))}
              </ul>
            </div>
          </div>
        ) : null}
      </div>

      <div className="mt-9">
        <OpenInApp appLink={sandwichAppLink(sandwich.id)} />
      </div>

      <p className="mt-5 text-xs text-muted">
        Tap “Open in Bread” to view this sandwich and invest in the app.
      </p>
    </main>
  );
}
